apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-robot-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: helm-2
    repoURL: https://github.com/<username>/node-robot
    targetRevision: HEAD
   syncPolicy: {}
