namespace:
  name: sandbox
 
service:
  port: 3000
  targetPort: 3000
  protocol: TCP
  type: ClusterIP

image:
  repository: <dockerhub-username>/node-robot
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

ports:
  containerPort: 3000
  protocol: TCP


