apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: flask-robot
  name: flask-robot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-robot
  template:
    metadata:
      labels:
        app: flask-robot
    spec:
      containers:
      - name: flask-robot
        image: <dockerhub-username>/flask-robot:latest
        imagePullPolicy: Always
        ports:
        - name: flaskport
          containerPort: 5000
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: flask-robot
  labels:
    app: flask-robot
spec:
  selector:
    app: flask-robot
  ports:
    - name: flask-robot
      protocol: TCP
      port: 5000
      targetPort: flaskport
  type: LoadBalancer

