namespace:
  name: sandbox
 
service:
  port: 5000
  targetPort: 5000
  protocol: TCP
  type: ClusterIP

image:
  repository: <dockerhub-username>/flask-robot
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

ports:
  containerPort: 5000
  protocol: TCP


