apiVersion: v1
kind: Service
metadata:
  labels: 
    app: node-robot
  name: node-robot 
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: node-robot
  type: {{ .Values.service.type }}
